SET foreign_key_checks = 0;
DROP TABLE IF EXISTS WFS_NOTICE CASCADE;
DROP TABLE IF EXISTS WFS_CATEGORY_B CASCADE;
DROP TABLE IF EXISTS WFS_CRAWLING_TARGET CASCADE;
DROP TABLE IF EXISTS WFS_EVENT CASCADE;
DROP TABLE IF EXISTS WFS_CATEGORY_C CASCADE;
DROP TABLE IF EXISTS WFS_BOOKMARK CASCADE;
DROP TABLE IF EXISTS WFS_AUTHORITY CASCADE;
DROP TABLE IF EXISTS WFS_CATEGORY_A CASCADE;
DROP TABLE IF EXISTS WFS_MEMBER CASCADE;
DROP TABLE IF EXISTS WFS_STATISTICS CASCADE;
SET foreign_key_checks = 1;


CREATE TABLE WFS_NOTICE (
	NOTICE_SEQ VARCHAR(40)   NOT NULL,
	MEMBER_SEQ VARCHAR(40)   NULL,    
	TITLE      VARCHAR(40)   NULL,     
	CONTENT    VARCHAR(2000) NULL,     
	WRITEDATE  VARCHAR(40)   NULL      
);

ALTER TABLE WFS_NOTICE
	ADD CONSTRAINT PK_WFS_NOTICE 
		PRIMARY KEY (
			NOTICE_SEQ 
		);

CREATE TABLE WFS_CATEGORY_B (
	CATEGORY_B_ID   VARCHAR(20)  NOT NULL, 
	CATEGORY_B_NAME VARCHAR(100) NULL,     
	CATEGORY_A_ID   VARCHAR(20)  NULL      
);

ALTER TABLE WFS_CATEGORY_B
	ADD CONSTRAINT PK_WFS_CATEGORY_B 
		PRIMARY KEY (
			CATEGORY_B_ID 
		);

CREATE TABLE WFS_CRAWLING_TARGET (
	CRAWLING_ID VARCHAR(20)   NOT NULL, 
	SITE_NAME   VARCHAR(1000) NULL,     
	KEYWORD     VARCHAR(100)  NULL      
);

ALTER TABLE WFS_CRAWLING_TARGET
	ADD CONSTRAINT PK_WFS_CRAWLING_TARGET 
		PRIMARY KEY (
			CRAWLING_ID 
		);

CREATE TABLE WFS_EVENT (
	EVENT_SEQ VARCHAR(40)  NOT NULL,
    MAINORSUB VARCHAR(20)  NOT NULL,
	TITLE      VARCHAR(100) NULL,     
	IMG       VARCHAR(200) NULL,     
	KEYWORD   VARCHAR(40)  NULL,
    STARTINGDAY   VARCHAR(40)  NULL,
    FINISHINGDAY   VARCHAR(40)  NULL,
    WRITEDATE   VARCHAR(40)  NULL
);

ALTER TABLE WFS_EVENT
	ADD CONSTRAINT PK_WFS_EVENT 
		PRIMARY KEY (
			EVENT_SEQ 
		);

CREATE TABLE WFS_CATEGORY_C (
	CATEGORY_C_ID   VARCHAR(20)  NOT NULL, 
	CATEGORY_C_NAME VARCHAR(100) NULL,     
	CATEGORY_B_ID   VARCHAR(20)  NULL      
);

ALTER TABLE WFS_CATEGORY_C
	ADD CONSTRAINT PK_WFS_CATEGORY_C 
		PRIMARY KEY (
			CATEGORY_C_ID 
		);

CREATE TABLE WFS_BOOKMARK (
	BOOKMARK_SEQ VARCHAR(40)   NOT NULL, 
	MEMBER_SEQ   VARCHAR(40)   NULL,     
	IMG          VARCHAR(100)  NULL,     
	GOODS_INFO   VARCHAR(2000) NULL,     
	PRICE        VARCHAR(20)   NULL,     
	STORE        VARCHAR(40)   NULL,     
	URI          VARCHAR(1000) NULL,
	STATUS 		 VARCHAR(20)   NULL
);

ALTER TABLE WFS_BOOKMARK
	ADD CONSTRAINT PK_WFS_BOOKMARK 
		PRIMARY KEY (
			BOOKMARK_SEQ 
		);

CREATE TABLE WFS_AUTHORITY (
	AUTHORITY_ID VARCHAR(20)  NOT NULL, 
	AUTHORITY    VARCHAR(100) NULL      
);

ALTER TABLE WFS_AUTHORITY
	ADD CONSTRAINT PK_WFS_AUTHORITY 
		PRIMARY KEY (
			AUTHORITY_ID 
		);

CREATE TABLE WFS_CATEGORY_A (
	CATEGORY_A_ID   VARCHAR(20)  NOT NULL, 
	CATEGORY_A_NAME VARCHAR(100) NULL      
);

ALTER TABLE WFS_CATEGORY_A
	ADD CONSTRAINT PK_WFS_CATEGORY_A
		PRIMARY KEY (
			CATEGORY_A_ID 
		);

CREATE TABLE WFS_MEMBER (
	MEMBER_SEQ   VARCHAR(40)  NOT NULL, 
	AUTHORITY_ID VARCHAR(20)  NULL,     
	EMAIL        VARCHAR(100) NOT NULL, 
	NAME         VARCHAR(100) NULL,     
	PHONE        VARCHAR(20)  NULL,     
	PASSWORD     VARCHAR(100)  NULL,     
	REGISTERDATE VARCHAR(40)  NULL      
);

ALTER TABLE WFS_MEMBER
	ADD CONSTRAINT PK_WFS_MEMBER 
		PRIMARY KEY (
			MEMBER_SEQ 
		);


ALTER TABLE WFS_NOTICE
	ADD CONSTRAINT FK_WFS_MEMBER_TO_WFS_NOTICE 
		FOREIGN KEY (
			MEMBER_SEQ 
		)
		REFERENCES WFS_MEMBER ( 
			MEMBER_SEQ 
		);


ALTER TABLE WFS_CATEGORY_B
	ADD CONSTRAINT FK_WFS_CATEGORY_A_TO_WFS_CATEGORY_B
		FOREIGN KEY (
			CATEGORY_A_ID 
		)
		REFERENCES WFS_CATEGORY_A ( 
			CATEGORY_A_ID 
		);

ALTER TABLE WFS_CATEGORY_C
	ADD CONSTRAINT FK_WFS_CATEGORY_B_TO_WFS_CATEGORY_C 
		FOREIGN KEY (
			CATEGORY_B_ID 
		)
		REFERENCES WFS_CATEGORY_B ( 
			CATEGORY_B_ID 
		);

ALTER TABLE WFS_BOOKMARK
	ADD CONSTRAINT FK_WFS_MEMBER_TO_WFS_BOOKMARK 
		FOREIGN KEY (
			MEMBER_SEQ 
		)
		REFERENCES WFS_MEMBER ( 
			MEMBER_SEQ 
		);

ALTER TABLE WFS_MEMBER
	ADD CONSTRAINT FK_WFS_AUTHORITY_TO_WFS_MEMBER 
		FOREIGN KEY (
			AUTHORITY_ID 
		)
		REFERENCES WFS_AUTHORITY ( 
			AUTHORITY_ID 
		);

CREATE TABLE WFS_STATISTICS (
	STATISTICS_SEQ VARCHAR(40)  NOT NULL,         
	KEYWORD    VARCHAR(40) NULL,     
	SEARCHDATE  VARCHAR(40)   NULL      
);

ALTER TABLE WFS_STATISTICS
	ADD CONSTRAINT PK_WFS_STATISTIC
		PRIMARY KEY (
			STATISTICS_SEQ 
		);
        

